### ISSUE TITLE
路由关联到控制器

### ISSUE THREAD

**Issue by DevOpserzhao** [win5do/go-microservice-demo#3]
怎么没有看到路由关联到控制器了，大佬

**Comment by win5do** [comment]
https://github.com/win5do/go-microservice-demo/blob/6215e1a410a301189ce969269eff09c9fc8d4235/pkg/server/grpc/gateway.go#L35

grpc service 是通过 grpc-gateway 启动的 http server 暴露，路由注册是在生成的代码里。
